	DECLARE_TERMINALS
		_colon_1C           , // 1
		_comma_1C           , // 2
		_crob_1C            , // 3
		_date_1C            , // 4
		_div_1C             , // 5
		_equal_1C           , // 6
		_grat_1C            , // 7
		_lBracket_1C        , // 8
		_lPar_1C            , // 9
		_label_1C           , // 10
		_less_1C            , // 11
		_literal_1C         , // 12
		_minus_1C           , // 13
		_mult_1C            , // 14
		_number_1C          , // 15
		_percent_1C         , // 16
		_period_1C          , // 17
		_plus_1C            , // 18
		_rBracket_1C        , // 19
		_rPar_1C            , // 20
		_semicolon_1C       , // 21
		_what_1C            , // 22
		_zname_1C           , // 23
		and_1C              , // 24
		break_1C            , // 25
		context_1C          , // 26
		continue_1C         , // 27
		do_1C               , // 28
		else_1C             , // 29
		elsif_1C            , // 30
		enddo_1C            , // 31
		endfunc_1C          , // 32
		endif_1C            , // 33
		endproc_1C          , // 34
		endtry_1C           , // 35
		except_1C           , // 36
		export_1C           , // 37
		for_1C              , // 38
		forward_1C          , // 39
		func_1C             , // 40
		goto_1C             , // 41
		if_1C               , // 42
		not_1C              , // 43
		or_1C               , // 44
		proc_1C             , // 45
		return_1C           , // 46
		then_1C             , // 47
		to_1C               , // 48
		try_1C              , // 49
		val_1C              , // 50
		var_1C              , // 51
		while_1C            , // 52
	END_TERMINALS
	DECLARE_NON_TERMINALS
		ASSIGNMENT          , // -1
		COMPARE             , // -2
		CONSTANT            , // -3
		ELSEBLOCK           , // -4
		ELSEIFBLOCK         , // -5
		EXPRBIN             , // -6
		EXPRESSION          , // -7
		FORBLOCK            , // -8
		IFBLOCK             , // -9
		JUMP                , // -10
		LITERAL             , // -11
		LOCALVAR            , // -12
		LOGIC               , // -13
		LOGICP              , // -14
		LVAL                , // -15
		LVAR                , // -16
		LVARIABLES          , // -17
		LVARS               , // -18
		METHEADER           , // -19
		METHNAME            , // -20
		METHOD              , // -21
		METHODS             , // -22
		MODUL               , // -23
		OPERATION           , // -24
		OPERATOR            , // -25
		PARAMLIST           , // -26
		PARAMS              , // -27
		REALPARAM           , // -28
		RVAL                , // -29
		STATEMENT           , // -30
		STATEMENTS          , // -31
		TRYBLOCK            , // -32
		VAR                 , // -33
		VARIABLES           , // -34
		VARS                , // -35
		WHILEBLOCK          , // -36
	END_NON_TERMINALS
	DECLARE_GRAMMAR(210,115)
