//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Enterprise.rc
//
#define IDI_ICON_SHORTCUT               1
#define IDR_MAIN0                       2
#define IDMODULE                        3
#define IDREFRESH                       4
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDC_GRIDBAR_GRIDBOX             102
#define IDC_RADIOCURSOR                 102
#define IDD_TEST008_DIALOG              102
#define IDC_TABBAR_TABBOX               103
#define IDD_PROCEDURE_LIST              103
#define IDD_MYFORM_FORM                 104
#define IDC_COMBO_FIND                  104
#define IDD_MOXCEL_DIALOG               104
#define IDC_POINTER_DRAG                104
#define IDR_MYFORM_TMPL                 105
#define IDR_METADATA                    106
#define ID_VIEW_RESIZABLE_BAR_1         106
#define IDD_FORM1C_2_FORM               107
#define IDC_MULTILINEEDITCURSOR         107
#define IDS_WINDOW_WINDOWS              107
#define IDR_FORM1C_2_TMPL               108
#define IDD_FORM1C_FORM                 110
#define IDR_FORM1C_TMPL                 111
#define _IDR_FORM1C_TMPL                111
#define IDC_BUTTONCURSOR                114
#define _EMPTY256                       115
#define IDC_CHECKCURSOR                 116
#define IDC_COMBOCURSOR                 117
#define IDC_DATECURSOR                  118
#define IDC_EDITCURSOR                  119
#define IDC_GROUPCURSOR                 120
#define IDC_LABELCURSOR                 121
#define _EMPTY261                       122
#define IDC_GRIDCURSOR                  122
#define IDC_LISTCURSOR                  123
#define IDC_TREECURSOR                  124
#define IDR_MAINFRAME                   128
#define IDR_ENTERPTYPE                  129
#define _IDR_ENTERPTYPE                 129
#define IDC_CHOOSELIST1                 130
#define IDC_EDIT1                       130
#define IDR_EDITBAR                     130
#define IDR_SAMPLETYPE                  131
#define IDB_EDIT_COPY                   132
#define IDS_DOC_SELECTOR                132
#define IDB_EDIT_PASTE                  133
#define IDS_RTF_TYPE                    133
#define IDB_EDIT_SECTION_ADD            134
#define IDB_EDIT_SECTION_DEL            135
#define IDB_EDIT_SECTIONS               136
#define IDB_EDIT_GRID                   137
#define IDB_EDIT_HEADERS                138
#define IDB_EDIT_LOCK                   139
#define IDB_EDIT_FREEZE                 140
#define IDB_CALCBTN                     141
#define IDR_TEXTTYPE                    142
#define _IDR_TEXTTYPE                   142
#define ID_EDIT_GRID                    200
#define IDB_FORMAT_COVERCELLS           201
#define ID_REPORTS                      202
#define ID_OBRABOTKA                    203
#define IDC_EDIT_STRING1                203
#define ID_JURNALDOC                    204
#define IDB_BITMAP1                     204
#define IDC_EDIT_STRING2                204
#define ID_SUBCONTO                     205
#define IDB_BITMAP2                     205
#define IDC_GRID                        205
#define IDR_MAINFRAME2                  206
#define IDB_BITMAP3                     206
#define IDC_MAIN_MENU                   206
#define IDD_CHOOSEVALUE                 207
#define IDR_GRID                        208
#define IDD_DIALOG1                     209
#define IDR_GRID_CONTEXT                210
#define IDR_MAINFRAME1                  211
#define IDB_EDIT_CUT                    212
#define IDD_DIALOG_SECTIONS             213
#define IDB_JURNALDOC                   214
#define IDD_CHOOSEVALUESMALL            214
#define IDR_GXLAYOUT1                   225
#define IDR_GXLAYOUT2                   226
#define IDD_METAOBJECT                  230
#define IDR_METADATATREE                231
#define IDC_CURSOR1                     235
#define IDB_MENU_BUTTON                 236
#define IDI_PROPERTY                    239
#define IDR_HELP                        241
#define IDD_INPUTSTRING                 242
#define IDD_DIALOGUNIT                  243
#define IDB_BITMAP4                     245
#define IDC_POINTER_DRAG2               248
#define IDC_PROGRESS                    249
#define IDD_DIALOG_GOTOLINE             249
#define IDC_SLIDER                      250
#define IDC_CURSOR2                     252
#define IDC_CURSOR3                     253
#define IDR_TOOLBAR1                    257
#define IDD_DIALOG2                     259
#define IDD_FIND_ALL_DIALOG             260
#define IDD_DIALOG3                     261
#define IDD_LAYERSELECT_FORM            261
#define IDD_DIALOG4                     262
#define IDR_TOOLFORM                    270
#define IDB_BITMAP9                     273
#define IDD_INPUTDATE                   274
#define IDD_INPUTNUMERIC                275
#define IDD_INPUTPERIOD                 276
#define IDD_CHANGEORDER                 278
#define IDR_CHANGEORDER                 279
#define IDD_DIALOG5                     281
#define IDC_WINDOWLIST_ACTIVATE         300
#define IDC_WINDOWLIST_CLOSE            301
#define IDC_WINDOWLIST_SAVE             302
#define IDC_WINDOWLIST_TILEHORZ         303
#define IDC_WINDOWLIST_MINIMIZE         304
#define IDC_WINDOWLIST_CASCADE          305
#define IDC_WINDOWLIST_TILEVERT         306
#define IDC_WINDOWLIST_LIST             307
#define ID_WINDOW_NEXT                  308
#define ID_WINDOW_PREVIOUS              309
#define ID_WINDOW_CLOSE_ALL             310
#define ID_WINDOW_SAVE_ALL              311
#define ID_WINDOW_MANAGE                312
#define ID_WINDOW_CLOSE                 313
#define IDS_WINDOW_MANAGE               314
#define ID_VIEW_FULLSCREEN              315
#define ID_VIEW_VIEWTAB                 316
#define IDD_WINDOW_MANAGE               330
#define IDR_TABVIEW_MENU                340
#define IDD_FORMOBJECT_FORM             400
#define IDR_FORMOBJECT_TMPL             401
#define IDD_SIMPLEPROPERTY_DIALOG       402
#define IDD_EDITDIALOG_FORM             404
#define IDR_EDITDIALOG_TMPL             405
#define _IDR_EDITDIALOG_TMPL            405
#define IDR_FORMEDITOR                  406
#define IDR_EDITFORMMENU                406
#define IDR_ALL_EDIT_MENU               406
#define IDD_FORMUNIT                    408
#define IDD_MYDATAEXCHANGE_DIALOG       409
#define IDR_LAYERSELECT_TMPL            411
#define _IDR_SAMPLETYPE                 412
#define _IDR_MAINFRAME                  413
#define IDC_NUMERICEDIT                 415
#define IDC_CUSTOM_GRID                 1000
#define IDC_TREE1                       1001
#define IDMYCANCEL                      1002
#define ID_ADD                          1003
#define IDC_RADIO1                      1004
#define IDC_RADIO_ALL                   1004
#define ID_DEL                          1005
#define ID_DEL_COLUMN                   1005
#define IDC_LISTBOXBAR                  1006
#define IDC_COMBO1                      1007
#define IDC_PARENT                      1007
#define IDB_BITMAP_SPLASH               1008
#define IDB_SUBCONTO                    1009
#define IDB_REPORTS                     1010
#define IDB_OBRABOTKA                   1011
#define ID_EDIT_ADD                     1012
#define IDB_DROPCBTN                    1012
#define ID_EDIT_DEL                     1013
#define IDB_CHOSECBTN                   1013
#define ID_EDIT_PROPERTY                1014
#define ID_VIEW_GRID                    1015
#define ID_EDIT_REMOVECOLS              1016
#define IDC_BUTTON_MXL                  1018
#define IDC_EDIT1_TEMP                  1201
#define IDC_BUTTON1                     1202
#define IDC_OK                          1202
#define IDC_TABCTRL                     1203
#define IDC_USE                         1203
#define IDC_OBJECTNAME                  1204
#define IDC_COMMENT                     1205
#define IDCLOSEFORM                     1206
#define IDC_OBJECTNAME2                 1207
#define IDC_DISPLAY_STATIC              1207
#define IDC_EDIT_NAME                   1208
#define IDC_EDIT_ALIAS                  1209
#define IDC_EDIT_COMMENT                1210
#define IDC_CHECK_VISIBLE               1211
#define IDC_STATIC1                     1212
#define IDC_STATIC2                     1213
#define IDC_STATIC3                     1214
#define IDC_STATIC0                     1215
#define IDC_CHECK_SORT                  1225
#define IDC_STATIC_DBDIR                1226
#define IDC_RADIO_EVENT                 1228
#define IDC_CHECK1                      1230
#define IDC_EDIT_INFO                   1231
#define IDC_TAB2                        1233
#define IDC_TAB1                        1234
#define IDC_ENTERPRISE_NAME             1235
#define IDC_DATETIMEPICKER1             1239
#define IDC_EDITNUMERIC                 1243
#define IDC_RADIO2                      1244
#define IDC_RADIO3                      1245
#define IDC_RADIO4                      1246
#define IDC_COMBO2                      1247
#define IDC_DATETIMEPICKER2             1248
#define IDC_DATETIMEPICKER3             1249
#define IDC_CHECK2                      1250
#define IDC_CHECK3                      1251
#define IDC_GRID1                       1256
#define IDC_EDIT_INFO1                  1257
#define IDB_ELB_ADD                     20516
#define IDB_ELB_DELETE                  20517
#define IDB_ELB_UP                      20518
#define IDB_ELB_DOWN                    20519
#define IDB_NEXTMONTH                   20520
#define IDB_PREVYEAR                    20521
#define IDB_NEXTYEAR                    20522
#define IDB_PREVMONTH                   20523
#define IDB_SECCALCEQUALS               20524
#define SEC_IDB_CHECK                   20525
#define IDS_SEC_CALC_CHCK               20635
#define IDS_SEC_CALC_BUT1               20636
#define IDS_SEC_CALC_BUT2               20637
#define IDS_SEC_CALC_BUT3               20638
#define IDS_SEC_CALC_BUT4               20639
#define IDS_SEC_CALC_BUT5               20640
#define IDS_SEC_CALC_BUT6               20641
#define IDS_SEC_CALC_BUT7               20642
#define IDS_SEC_CALC_BUT8               20643
#define IDS_SEC_CALC_BUT9               20644
#define IDS_SEC_CALC_BUT10              20645
#define IDS_SEC_CALC_BUT11              20646
#define IDS_SEC_CALC_BUT12              20647
#define IDS_SEC_CALC_BUT13              20648
#define IDS_SEC_CALC_BUT14              20649
#define IDS_SEC_CALC_BUT15              20650
#define IDS_SEC_CALC_BUT16              20651
#define IDS_SEC_CALC_BUT17              20652
#define IDS_SEC_CALC_BUT18              20653
#define IDS_SEC_CALC_EXTPT              20654
#define IDS_SEC_SBAR_TIP1               20655
#define IDS_SEC_CALC_TEXTPT             20656
#define IDS_SEC_SBAR_TIP2               20657
#define IDC_TOOLBAR_DRAGADD             20691
#define IDC_TOOLBAR_HORZDRAG            20692
#define IDC_PAN_OVERVIEW                20693
#define IDC_FORMOBJECT                  20694
#define IDC_POINTER_DRAG3               20695
#define IDC_BUTTON_TAB                  20696
#define IDS_SEC_TBOX_WNDT               21052
#define IDS_SEC_TBOX_MENU1              21053
#define IDS_SEC_TBOX_MENU2              21054
#define IDS_SEC_TBOX_TTIP               21055
#define SECAH_IDB_ARROW                 21211
#define SECAH_IDB_NOTFOUND              21212
#define SECAH_IDD_CustomizeToolbox      21214
#define SECAH_IDR_EDIT                  21218
#define IDR_MODULE                      21219
#define IDB_BITMAP5                     21220
#define IDR_CONFIGTOOLBAR               21221
#define IDR_LAYER                       21222
#define IDB_CMN_DOWNARROW               23000
#define IDB_CMN_RIGHTARROW              23001
#define IDB_BITMAP6                     23002
#define IDB_BITMAP7                     23003
#define IDB_BITMAP8                     23004
#define IDB_EDIT_NEW                    23005
#define IDB_EDIT                        23006
#define IDB_EDIT_MAKET                  23007
#define IDB_EDIT_FORM                   23008
#define IDB_EDIT_MODULE                 23009
#define IDB_EDIT_DOC                    23010
#define ID_TOOL_GRID                    30806
#define ID_EDIT_INSERTROW               30807
#define IDS_MRC_STARTDOCKING            31773
#define ID_FILE_HEADERFOOTER            31778
#define ID_VIEW_PROPERTIES              31779
#define ID_FORMAT_FREEZECOLS            31780
#define ID_MRC_CLEAR                    31781
#define ID_FORMAT_UNFREEZECOLS          31782
#define ID_MRC_ALLOWDOCKING             31783
#define ID_MRC_HIDE                     31784
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_MRC_MDIFLOAT                 32770
#define ID_FORMAT_CELLS                 32771
#define ID_DYNBUTTONRADIO               32772
#define ID_DYNBUTTONDATE                32773
#define ID_FORMAT_FREEZEROWS            32774
#define ID_FORMAT_UNFREEZEROWS          32775
#define ID_FORMAT_STYLES                32776
#define ID_EDIT_SECTIONS                32777
#define ID_EDIT_HEADERS                 32778
#define ID_EDIT_LOCK                    32779
#define ID_DYNBUTTONLISTBOX             32780
#define ID_EDIT_FREEZE                  32781
#define ID_VIEW_READONLY                32784
#define ID_FORMAT_COVERCELLS            32785
#define ID_FORMAT_ALIGN_LEFT            32789
#define ID_FORMAT_ALIGN_CENTER          32790
#define ID_FORMAT_ALIGN_RIGHT           32791
#define ID_VIEW_USERACTIONS             32793
#define ID_FORMAT_REMOVECOVER           32794
#define ID_FORMAT_STYLE_BOLD            32795
#define ID_READ_ONLY                    32795
#define ID_FORMAT_STYLE_ITALIC          32796
#define ID_EDIT_DISABLEBSATSOL          32796
#define ID_VIEW_SPLITTERVIEW            32797
#define ID_EDIT_DISABLEDRAGANDDROP      32797
#define ID_FORMAT_STYLE_UNDERLINE       32798
#define ID_VIEW_GRIDBAR                 32799
#define ID_VIEW_TABBAR                  32800
#define ID_TEST_CDERGRIDDIALOG          32802
#define ID_VIEW_DIALOGBAR               32803
#define ID_VIEW_ZOOMIN                  32804
#define ID_VIEW_ZOOMOUT                 32805
#define ID_VIEW_100                     32806
#define ID_EDIT_INSERTCOL               32808
#define ID_VIEW_WYSIWIG                 32811
#define ID_EDIT_REMOVEROWS              32814
#define ID_FORMAT_LOOKUP                32815
#define ID_FORMAT_RESIZEROWS            32828
#define ID_FORMAT_RESIZECOLS            32829
#define ID_DYNBUTTONLABEL               32843
#define ID_DYNBUTTONCOMBO               32844
#define ID_DYNBUTTONCHECK               32846
#define ID_TOOL_EDIT                    32901
#define ID_VIEWMESSAGEWINDOW            33002
#define ID_REMOVE_ALL                   33003
#define ID_VIEWDEBUGMESSAGEWINDOW       33003
#define ID_BUTTON_RUN                   33004
#define IDR_NEW                         33005
#define IDR_EDIT                        33006
#define IDR_REMOVE                      33007
#define ID_VIEW_STACK                   33008
#define ID_BUTTON_ENTERPRISE            33010
#define ID_BUTTON_COMPILE               33011
#define ID_PROPERTY                     33012
#define ID_TOOL_EDITOR                  33013
#define ID_SEND_TO_BACK                 33014
#define ID_BRING_TO_FRONT               33015
#define ID_CNTERINVIEW_VERT             33016
#define ID_CNTERINVIEW_HORIZ            33017
#define ID_SPACEEVENLY_ACROSS           33018
#define ID_SPACEEVENLY_DOWN             33019
#define ID_DYNBUTTON                    33020
#define ID_SELECT_ALL                   33021
#define ID_PROPERTYBAR                  33022
#define ID_CONFIG                       33025
#define ID_ENTERPRISE                   33026
#define ID_DYNBUTTONGRID                33027
#define ID_DYNBUTTONTREE                33028
#define ID_OPENCONFIG                   33029
#define ID_INSERT_FORM                  33030
#define ID_SAVEFORM                     33031
#define ID_REPLACEFORM                  33032
#define ID_BUTTONPROGRESS               33035
#define ID_BUTTONSLIDER                 33036
#define ID_BUTTONCOMMENT                33037
#define ID_BUTTONDELCOMMENT             33038
#define ID_BUTTONPROC                   33039
#define ID_BUTTONGOTOLINE               33041
#define ID_BUTTONFORMAT                 33042
#define ID_HELP_SEARCH_COMBO            33044
#define ID_VIEW_LIKE_OFFICE_2K          33045
#define ID_VIEW_LIKE_OFFICE_XP          33046
#define ID_MODULE_CONFIG                33047
#define ID_MODULE_RUN                   33048
#define ID_EDIT_DEBUG_POINT             33051
#define ID_NEXT_DEBUG                   33053
#define ID_NEXT_DEBUG_OVER              33055
#define ID_RUN_DEBUG                    33056
#define ID_PAUSE_DEBUG                  33057
#define ID_STOP_DEBUG                   33058
#define ID_STOP_PROGRAM                 33060
#define ID_ADD_COLUMN                   33063
#define ID_PROP_COLUMN                  33065
#define ID_LEFT_COLUMN                  33066
#define ID_RIGHT_COLUMN                 33067
#define ID_BUTTONFORMOBJECT             33068
#define ID_POST_SHOW                    33069
#define IDR_NEW_FOLDER                  33073
#define ID_EDIT_GOTO                    33074
#define ID_CLOSE                        33075
#define ID_GRID_COVERED                 33076
#define ID_GRID_ADD_SECTION             33077
#define ID_GRID_                        33078
#define ID_GRID_SECTION                 33079
#define ID_BUTTON33080                  33080
#define ID_GRID_HEADER                  33081
#define ID_GRID_READONLY                33083
#define ID_GRID_SECTION_REMOVE          33084
#define ID_GRID_SETKA                   33085
#define ID_GRID_VIEW_SECTION            33086
#define ID_ALL_FIND                     33087
#define ID_BUTTON_TAB                   33088
#define ID_LAYERS                       33091
#define ID_NEW_LAYER                    33092
#define ID_EDIT_LAYER                   33093
#define ID_DEL_LAYER                    33094
#define ID_UP_LAYER                     33095
#define ID_DOWN_LAYER                   33096
#define ID_VIEW_FORM                    33098
#define ID_VIEW_MODULE                  -32437
#define ID_VIEW_DESCRIPTION             -32436
#define ID_BUTTON33102                  33102
#define ID_ORDER_ELEMENTS               33103
#define ID_UP                           33104
#define ID_DOWN                         33105
#define ID_ROW_HEIGTH                   33106
#define ID_COL_WIDTH                    33107
#define ID_ROW_HEIGHT                   33108
#define ID_ACCEL33109                   33109
#define ID_VIEW_TABLELIST               -32426
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_FORMAT_BLOCK                 37199
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_CLEAR_BOOKMARKS         37220
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define ID_EDIT_INDICATOR_COL           37900
#define ID_EDIT_INDICATOR_READ          37901
#define ID_EDIT_INDICATOR_CRLF          37902
#define ID_EDIT_INDICATOR_POSITION      37903
#define ID_DYNBUTTONGROUP               40001
#define ID_DYNBUTTONLEFTALIGN           40003
#define ID_DYNBUTTONTOPALIGN            40005
#define ID_DYNBUTTONBOTTOMALIGN         40006
#define ID_DYNBUTTONMAKESAMEWIDTH       40010
#define ID_DYNBUTTONMAKESAMEHEIGHT      40011
#define ID_DYNBUTTONMAKESAMESIZE        40012
#define ID_DYNBUTTONRIGHTALIGN          40015
#define ID_DYNBUTTONEDIT                40016
#define ID_USE_GRID                     40017
#define ID_EDIT_ALLIGN_GRID             40017
#define SECAH_ID_LAYOUT_EDIT            43714
#define SECAH_IDC_CONTROLS              43743
#define AFX_IDS_APP_TITLE2              57346
#define AFX_IDS_IDLEMESSAGE2            57347
#define ID_FILE_NEW2                    57605
#define ID_FILE_OPEN2                   57608
#define ID_FILE_CLOSE2                  57610
#define ID_FILE_SAVE2                   57611
#define ID_FILE_SAVE_AS2                57612
#define ID_FILE_PAGE_SETUP2             57613
#define ID_FILE_PRINT_SETUP2            57614
#define ID_FILE_PRINT2                  57615
#define ID_FILE_PRINT_PREVIEW2          57617
#define ID_EDIT_COPY2                   57636
#define ID_EDIT_CUT2                    57638
#define ID_EDIT_FIND2                   57639
#define ID_EDIT_PASTE2                  57640
#define ID_EDIT_REPEAT2                 57641
#define ID_EDIT_REPLACE2                57642
#define ID_EDIT_SELECT_ALL2             57644
#define ID_EDIT_UNDO2                   57645
#define ID_EDIT_REDO2                   57646
#define ID_WINDOW_CASCADE2              57652
#define ID_WINDOW_TILE_HORZ2            57653
#define ID_WINDOW_TILE_VERT2            57654
#define ID_WINDOW_SPLIT2                57655
#define ID_APP_ABOUT2                   57666
#define ID_APP_EXIT2                    57667
#define ID_VIEW_TOOLBAR2                59394
#define ID_VIEW_STATUS_BAR2             59395
#define ID_LISTBOXBAR                   0xe883
#define IDR_MAIN_TOOLBAR                59524

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        282
#define _APS_NEXT_COMMAND_VALUE         33111
#define _APS_NEXT_CONTROL_VALUE         1258
#define _APS_NEXT_SYMED_VALUE           417
#endif
#endif
