//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SECRES.RC
//
#ifndef __SECRES_H__
#define __SECRES_H__

#include "cmnres.h"

//
// Header include diagnostics
//
#if defined(WIN32) && defined(SEC_DBG_HEADER_DIAGNOSTICS)
	#pragma message ( __TIME__ ":  include " __FILE__ )
#endif
///////////////////////////////////////////////
// non-movable resources
///////////////////////////////////////////////
#define IDC_COMMON_CONTROL_SUBCLASS_NETWORK                 1037
#define IDC_COMMON_CONTROL_SUBCLASS_HELP_BUTTON             1038
#define IDC_COMMON_CONTROL_SUBCLASS_READ_ONLY               1040
#define IDC_COMMON_CONTROL_SUBCLASS_STATIC_DIR              1088
#define IDC_COMMON_CONTROL_SUBCLASS_STATIC_TYPE             1089
#define IDC_COMMON_CONTROL_SUBCLASS_STATIC_FILE_NAME        1090
#define IDC_COMMON_CONTROL_SUBCLASS_STATIC_DRIVE            1091
#define IDC_COMMON_CONTROL_SUBCLASS_FILE_LIST               1120
#define IDC_COMMON_CONTROL_SUBCLASS_DIR_LIST                1121
#define IDC_COMMON_CONTROL_SUBCLASS_TYPE_LIST               1136
#define IDC_COMMON_CONTROL_SUBCLASS_DRIVE_LIST              1137
#define IDC_COMMON_CONTROL_SUBCLASS_FILE_NAME               1152
#define IDC_COMMON_CONTROL_SUBCLASS_DIRSELECT               2000
/////////////////////////////////////////////////////////
// OT Standard lower resource range 20500 - 20999
// IDD_, IDB_, IDI_, IDS_
/////////////////////////////////////////////////////////
#define IDD_TIP_OF_DAY                  20500
#define IDD_WINDOWS                     20501
#define IDD_OPEN_WORKSPACE              20502
#define IDD_SAVE_WORKSPACE              20503
#define IDD_NEW_WORKSPACE               20504
#define IDD_DELETE_WORKSPACE            20505
#define IDD_COMDLG32                    20506
#define IDD_SHORTCUT_KEYS               20507
#define IDD_ASSIGN_SHORTCUT             20508
#define IDD_TOOLBAR_CUSTOMIZE           20509
#define IDD_TOOLBARS                    20510
#define IDD_TOOLBAR_NEW                 20511
#define IDD_UTM_USER_TOOLS              20512
#define IDD_TOOLBARS_PAGE               20513
#define IDI_MDICTRLBAR                  20514
#define IDI_TOD_LIGHT                   20515
#define IDB_ELB_ADD                     20516
#define IDB_ELB_DELETE                  20517
#define IDB_ELB_UP                      20518
#define IDB_ELB_DOWN                    20519
#define IDB_NEXTMONTH                   20520
#define IDB_PREVYEAR                    20521
#define IDB_NEXTYEAR                    20522
#define IDB_PREVMONTH                   20523
#define IDB_SECCALCEQUALS               20524
#define SEC_IDB_CHECK                   20525
#define IDS_SHORTCUT_SELECT_BEFORE_REMOVE 20526
#define IDS_SHORTCUT_SELECT_BEFORE_CREATE 20527
#define IDS_SHORTCUT_RESET_WARN         20528
#define IDS_SHORTCUT_UNASSIGNED         20529
#define IDS_SHORTCUT_PERMANENT          20530
#define IDS_ELB_ADD                     20531
#define IDS_ELB_DELETE                  20532
#define IDS_ELB_UP                      20533
#define IDS_ELB_DOWN                    20534
#define IDS_SEC_STARTDOCKING            20535
#define IDS_TOOLBAR_RESET               20536
#define IDS_TOOLBAR_DELETE              20537
#define IDS_TOOLBAR_CUSTOMIZE           20538
#define IDS_SECCALENDAR_DAY1ABBR        20539
#define IDS_SECCALENDAR_DAY1FULL        20540
#define IDS_SECCALENDAR_DAY2ABBR        20541
#define IDS_SECCALENDAR_DAY2FULL        20542
#define IDS_SECCALENDAR_DAY3ABBR        20543
#define IDS_SECCALENDAR_DAY3FULL        20544
#define IDS_SECCALENDAR_DAY4ABBR        20545
#define IDS_SECCALENDAR_DAY4FULL        20546
#define IDS_SECCALENDAR_DAY5ABBR        20547
#define IDS_SECCALENDAR_DAY5FULL        20548
#define IDS_SECCALENDAR_DAY6ABBR        20549
#define IDS_SECCALENDAR_DAY6FULL        20550
#define IDS_SECCALENDAR_DAY7ABBR        20551
#define IDS_SECCALENDAR_DAY7FULL        20552
#define IDS_SECCALENDAR_MONTH1ABBR      20553
#define IDS_SECCALENDAR_MONTH1FULL      20554
#define IDS_SECCALENDAR_MONTH2ABBR      20555
#define IDS_SECCALENDAR_MONTH2FULL      20556
#define IDS_SECCALENDAR_MONTH3ABBR      20557
#define IDS_SECCALENDAR_MONTH3FULL      20558
#define IDS_SECCALENDAR_MONTH4ABBR      20559
#define IDS_SECCALENDAR_MONTH4FULL      20600
#define IDS_SECCALENDAR_MONTH5ABBR      20601
#define IDS_SECCALENDAR_MONTH5FULL      20602
#define IDS_SECCALENDAR_MONTH6ABBR      20603
#define IDS_SECCALENDAR_MONTH6FULL      20604
#define IDS_SECCALENDAR_MONTH7ABBR      20605
#define IDS_SECCALENDAR_MONTH7FULL      20606
#define IDS_SECCALENDAR_MONTH8ABBR      20607
#define IDS_SECCALENDAR_MONTH8FULL      20608
#define IDS_SECCALENDAR_MONTH9ABBR      20609
#define IDS_SECCALENDAR_MONTH9FULL      20610
#define IDS_SECCALENDAR_MONTH10ABBR     20611
#define IDS_SECCALENDAR_MONTH10FULL     20612
#define IDS_SECCALENDAR_MONTH11ABBR     20613
#define IDS_SECCALENDAR_MONTH11FULL     20614
#define IDS_SECCALENDAR_MONTH12ABBR     20615
#define IDS_SECCALENDAR_MONTH12FULL     20616
#define IDS_SECCALCENTER                20617
#define IDS_SECCALCERROR                20618
#define IDS_MENUBAR                     20619
#define SEC_IDR_SHORCUTLIST_MENU        20620
#define IDS_SEC_SCRIP_WNTXT             20621
#define IDS_SEC_CONT_PLIST17            20622
#define IDS_SEC_CONT_PLIST18            20623
#define IDS_SEC_BEDIT_TEXT1             20624
#define IDS_SEC_BEDIT_TEXT2             20625
#define IDS_SEC_BEDIT_TEXT3             20626
#define IDS_SEC_CEDIT_FMAT1             20627
#define IDS_SEC_CEDIT_MNU1              20628
#define IDS_SEC_CEDIT_MNU2              20629
#define IDS_SEC_CEDIT_MNU3              20630
#define IDS_SEC_CEDIT_MNU4              20631
#define IDS_SEC_CEDIT_MNU5              20632
#define IDS_SEC_CEDIT_MNU6              20633
#define IDS_SEC_LBEDIT_DLGT             20634
#define IDS_SEC_CALC_CHCK               20635
#define IDS_SEC_CALC_BUT1               20636
#define IDS_SEC_CALC_BUT2               20637
#define IDS_SEC_CALC_BUT3               20638
#define IDS_SEC_CALC_BUT4               20639
#define IDS_SEC_CALC_BUT5               20640
#define IDS_SEC_CALC_BUT6               20641
#define IDS_SEC_CALC_BUT7               20642
#define IDS_SEC_CALC_BUT8               20643
#define IDS_SEC_CALC_BUT9               20644
#define IDS_SEC_CALC_BUT10              20645
#define IDS_SEC_CALC_BUT11              20646
#define IDS_SEC_CALC_BUT12              20647
#define IDS_SEC_CALC_BUT13              20648
#define IDS_SEC_CALC_BUT14              20649
#define IDS_SEC_CALC_BUT15              20650
#define IDS_SEC_CALC_BUT16              20651
#define IDS_SEC_CALC_BUT17              20652
#define IDS_SEC_CALC_BUT18              20653
#define IDS_SEC_CALC_EXTPT              20654
#define IDS_SEC_SBAR_TIP1               20655
#define IDS_SEC_CALC_TEXTPT             20656
#define IDS_SEC_SBAR_TIP2               20657
#define IDS_SEC_SBAR_TIP3               20658
#define IDS_SEC_FDIC_STR                20659
#define IDS_SEC_FDIM_MNU                20660
#define IDS_SEC_SPLS_TITL1              20661
#define IDS_SEC_SPLS_TITL2              20662
#define IDS_SEC_STOD_LTXT               20663
#define IDS_SEC_WSMGR_MNU1              20664
#define IDS_SEC_WSMGR_MSG               20665
#define IDS_SEC_WSMGR_FOR1              20666
#define IDS_SEC_WSMGR_FOR2              20667
#define IDS_SEC_WSMGR_FOR3              20668
#define IDS_SEC_WSMGR_FOR4              20669
#define IDS_SEC_WSMGR_FOR5              20670
#define IDS_SEC_WSMGR_WTXT1             20671
#define IDS_SEC_WSMGR_WTXT2             20672
#define IDS_SEC_WSMGR_MSG2              20673
#define IDS_SEC_TBMGR_FOR1              20674
#define IDS_SEC_CRPT_MSG1               20675
#define IDS_SEC_PWND_TITL               20676
#define IDS_SEC_SCUT_TXT1               20677
#define IDS_SEC_HKEY_TXT1               20678
#define IDS_SEC_TNDLG_TXT               20679
#define IDS_SEC_TLDLG_EDT1              20680
#define IDS_SEC_TLDLG_EDT2              20681
#define IDS_SEC_TLDLG_EDT3              20682
#define IDS_SEC_TLDLG_MNU1              20683
#define IDS_SEC_TLDLG_MSG1              20684
#define IDS_WORKSPACE_MGR_EX_MRU_NONE   20685
#define IDS_WORKSPACE_MGR_EX_OPEN_WORKSPACE	20686
#define IDS_WORKSPACE_MGR_EX_WORKSPACES	20687
#define IDS_WORKSPACE_MGR_EX_ALLFILES   20688
#define IDS_WORKSPACE_MGR_EX_SAVE_WORKSPACE 20689
#define IDS_WORKSPACE_MGR_EX_INVALID_WORKSPACE 20690
#define IDC_TOOLBAR_DRAGADD             20691
#define IDC_TOOLBAR_HORZDRAG            20692
#define IDC_PAN_OVERVIEW                20693

/////////////////////////////////////////////////////////
// OT Standard upper resource range 43000 - 43499
// ID_, IDC_
/////////////////////////////////////////////////////////
#define ID_SAVE_WORKSPACE               43000
#define ID_OPEN_WORKSPACE               43001
#define ID_DELETE_WORKSPACE             43002
#define ID_CREATE_WORKSPACE             43003
#define ID_WINDOW_WINDOWS               43004
#define ID_FILE_LOADWORKSPACE           43005
#define ID_FILE_SAVEWORKSPACE           43006
#define ID_WORKSPACE_NEW                43007
#define ID_WORKSPACE_OPEN               43008
#define ID_WORKSPACE_SAVE               43009
#define ID_PROJECT_WORKSPACE_SAVEAS     43010
#define ID_PROJECT_WORKSPACE_CLOSE      43011
#define ID_WORKSPACE_CLOSE              43012
#define ID_WORKSPACE_SAVEAS             43013
#define ID_WORKSPACE_DELETE             43014
#define ID_FDI_WINDOW_1                 43015
#define ID_FDI_WINDOW_2                 43016
#define ID_FDI_WINDOW_3                 43017
#define ID_FDI_WINDOW_4                 43018
#define ID_FDI_WINDOW_5                 43019
#define ID_FDI_WINDOW_6                 43020
#define ID_FDI_WINDOW_7                 43021
#define ID_FDI_WINDOW_8                 43022
#define ID_FDI_WINDOW_9                 43023
#define ID_FDI_WINDOW_10                43024
#define ID_FDI_WINDOW_11                43025
#define ID_FDI_WINDOW_12                43026
#define ID_FDI_WINDOW_13                43027
#define ID_FDI_WINDOW_14                43028
#define ID_FDI_WINDOW_15                43029
#define ID_FDI_WINDOW_16                43030
#define ID_WORKSPACE_1                  43031
#define ID_WORKSPACE_2                  43032
#define ID_WORKSPACE_3                  43033
#define ID_WORKSPACE_4                  43034
#define ID_WORKSPACE_5                  43035
#define ID_WORKSPACE_6                  43036
#define ID_WORKSPACE_7                  43037
#define ID_WORKSPACE_8                  43038
#define ID_WORKSPACE_SPACES             43039
#define ID_SEC_ALLOWDOCKING             43040
#define ID_SEC_HIDE                     43041
#define ID_SEC_MDIFLOAT                 43042
#define ID_UTM_TOOLS_CUSTOMIZE          43043
#define ID_UTM_TOOLS_USER_1             43044
#define ID_UTM_TOOLS_USER_2             43045
#define ID_UTM_TOOLS_USER_3             43046
#define ID_UTM_TOOLS_USER_4             43047
#define ID_UTM_TOOLS_USER_5             43048
#define ID_UTM_TOOLS_USER_6             43049
#define ID_UTM_TOOLS_USER_7             43050
#define ID_UTM_TOOLS_USER_8             43051
#define ID_UTM_TOOLS_USER_9             43052
#define ID_DONE                         43053
#define SEC_ID_SHORTCUTLIST_LARGEICON   43054
#define SEC_ID_SHORTCUTLIST_SMALLICON   43055
#define IDC_TOD_OK_BUTTON               43056
#define IDC_TOD_NEXT_BUTTON             43057
#define IDC_TOD_PREV_BUTTON             43058
#define IDC_TOD_HELP_BUTTON             43059
#define IDC_TOD_SHOW_CHECK              43060
#define IDC_TOD_GROUPBOX                43061
#define IDC_SHORTCUT_CREATE             43063
#define IDC_SHORTCUT_REMOVE             43064
#define IDC_SHORTCUT_KEY_LIST           43065
#define IDC_SHORTCUT_DESCRIPTION        43066
#define IDC_SHORTCUT_RESET              43067
#define IDC_SHORTCUT_NAME_LIST          43068
#define IDC_SHORTCUT_HOTKEY             43069
#define IDC_SHORTCUT_ASSIGNMENT_TEXT    43070
#define IDC_SHORTCUT_ASSIGNMENT_TITLE   43071
#define IDC_WORKSPACE_LIST              43072
#define IDC_WINDOWLIST                  43073
#define IDC_CLOSEWINDOW                 43074
#define IDC_SAVE                        43075
#define IDC_EDITBOX                     43076
#define IDC_WINDOWSHELP                 43077
#define IDC_UTM_LIST                    43078
#define IDC_UTM_ADD                     43079
#define IDC_UTM_REMOVE                  43080
#define IDC_UTM_MOVE_UP                 43081
#define IDC_UTM_MOVE_DOWN               43082
#define IDC_UTM_COMMAND                 43083
#define IDC_UTM_STATIC_COMMAND          43084
#define IDC_UTM_MENU_TEXT               43085
#define IDC_UTM_ARGUMENTS               43086
#define IDC_UTM_INITIAL_DIRECTORY       43087
#define IDC_UTM_STATIC_MENU_TEXT        43088
#define IDC_UTM_STATIC_ARGUMENTS        43089
#define IDC_UTM_STATIC_INITIAL_DIRECTORY 43090
#define IDC_TOOLBAR_FRAME               43093
#define IDC_TOOLBAR_LIST                43094
#define IDC_TOOLBAR_DESCRIPTION         43095
#define IDC_TOOLBAR_NAME_EDIT           43096
#define IDC_TOOLBAR_STATIC              43097
#define IDC_TOOLBAR_NEW                 43098
#define IDC_TOOLBAR_CUSTOMIZE           43099
#define IDC_TOOLBAR_RESET               43100
#define IDC_TOOLBAR_TOOLTIPS            43101
#define IDC_TOOLBAR_NAME                43102
#define IDC_TOOLBAR_LARGEBTNS           43103
#define IDC_TOOLBAR_COOLLOOK            43104
#define IDC_WORKSPACE_MGR_STATIC        43105
#define IDC_SEC_DEFAULT					43106	// default for our controls

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#endif // __SECRES_H__
