//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vis1cpp.rc
//
#define IDS_PROJNAME                    100
#define IDR_VIS1CPPPLUGIN               102
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDD_EMPTY                       1002
#define IDD_ROOT                        1003
#define IDD_CLASS                       1004
#define IDI_CLASS                       1006
#define IDI_PRIVMET                     1007
#define IDR_COCLASSINFO                 1008
#define IDI_DECLPROC                    1009
#define IDI_PRIVMEMB                    1010
#define IDR_COCLASSES                   1011
#define IDI_OPENMEMB                    1012
#define IDI_WRCCPACE                    1013
#define IDI_DEFFILE                     1014
#define IDI_OPENMET                     1015
#define IDI_BASECLASSES                 1016
#define IDR_ACCELERATOR1                1017
#define IDR_CODEFFILES                  1018
#define IDR_CODEFFILE                   1019
#define IDR_TOOLBAR1                    1020
#define IDR_MAIN                        10000
#define ID_BUTTON32772                  32772
#define ID_BUTTON32773                  32773
#define ID_TEST_TEST1                   32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1025
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           1020
#endif
#endif
